// run_nbg.cpp — auto-generated by lower_to_timvx.py (--target=nbg).
// Generic VIPLite NBG runner: vip_init → vip_create_network →
// vip_prepare_network → query I/O → wire buffers → vip_run_network.
// No tim::vx, no OVXLIB on the runtime path.
//
// usage: ./<base>_run_nbg <model.nbg> <input0.bin> [<input1.bin> ...]
//
// The number / shape / dtype of inputs comes from the NBG itself
// (vip_query_input). The runner only validates that the on-disk size
// matches the buffer's expected byte count. Outputs are dequantized
// using their NBG-recorded (scale, zp) for the print summary, the
// same way runner_main.cpp does it.

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iterator>
#include <numeric>
#include <vector>

#include "vip_lite.h"

namespace {

constexpr size_t kPrintFirst = 16;

#define VIP_CHECK(call, ...)                                              \
  do {                                                                    \
    vip_status_e _s = (call);                                             \
    if (_s != VIP_SUCCESS) {                                              \
      std::fprintf(stderr, #call " failed: status=%d\n", static_cast<int>(_s)); \
      __VA_ARGS__;                                                        \
      return 3;                                                           \
    }                                                                     \
  } while (0)

std::vector<uint8_t> read_file(const char* path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) {
    std::fprintf(stderr, "cannot open: %s\n", path);
    std::exit(1);
  }
  std::streamsize n = f.tellg();
  f.seekg(0, std::ios::beg);
  std::vector<uint8_t> buf(static_cast<size_t>(n));
  f.read(reinterpret_cast<char*>(buf.data()), n);
  return buf;
}

// Bytes per element for each VIP buffer format. Mirrors the format
// list in vip_lite.h; only those a model could plausibly emit are
// actually exercised here.
size_t format_bytes(vip_enum fmt) {
  switch (fmt) {
    case VIP_BUFFER_FORMAT_FP32:   return 4;
    case VIP_BUFFER_FORMAT_FP16:   return 2;
    case VIP_BUFFER_FORMAT_BFP16:  return 2;
    case VIP_BUFFER_FORMAT_UINT8:  return 1;
    case VIP_BUFFER_FORMAT_INT8:   return 1;
    case VIP_BUFFER_FORMAT_UINT16: return 2;
    case VIP_BUFFER_FORMAT_INT16:  return 2;
    case VIP_BUFFER_FORMAT_INT32:  return 4;
    case VIP_BUFFER_FORMAT_UINT32: return 4;
    case VIP_BUFFER_FORMAT_INT64:  return 8;
    case VIP_BUFFER_FORMAT_UINT64: return 8;
    case VIP_BUFFER_FORMAT_FP64:   return 8;
    default:                       return 0;
  }
}

// Fill out the create-params for a network input/output by chaining
// vip_query_input/output for each property. Returns the byte size of
// the buffer (product of dims × format bytes).
size_t fill_io_params(vip_network net, vip_uint32_t idx, bool is_input,
                       vip_buffer_create_params_t& out) {
  std::memset(&out, 0, sizeof(out));
  auto query = is_input ? &vip_query_input : &vip_query_output;

  query(net, idx, VIP_BUFFER_PROP_NUM_OF_DIMENSION, &out.num_of_dims);
  query(net, idx, VIP_BUFFER_PROP_SIZES_OF_DIMENSION, &out.sizes[0]);
  query(net, idx, VIP_BUFFER_PROP_DATA_FORMAT, &out.data_format);
  query(net, idx, VIP_BUFFER_PROP_QUANT_FORMAT, &out.quant_format);
  if (out.quant_format == VIP_BUFFER_QUANTIZE_TF_ASYMM) {
    query(net, idx, VIP_BUFFER_PROP_TF_SCALE, &out.quant_data.affine.scale);
    query(net, idx, VIP_BUFFER_PROP_TF_ZERO_POINT,
          &out.quant_data.affine.zeroPoint);
  } else if (out.quant_format == VIP_BUFFER_QUANTIZE_DYNAMIC_FIXED_POINT) {
    query(net, idx, VIP_BUFFER_PROP_FIXED_POINT_POS,
          &out.quant_data.dfp.fixed_point_pos);
  }
  out.memory_type = VIP_BUFFER_MEMORY_TYPE_DEFAULT;

  size_t numel = 1;
  for (vip_uint32_t i = 0; i < out.num_of_dims; ++i) numel *= out.sizes[i];
  return numel * format_bytes(out.data_format);
}

void print_io(const char* tag, vip_uint32_t idx,
              const vip_buffer_create_params_t& p, size_t bytes) {
  std::printf("  %s[%u]: dims=", tag, idx);
  for (vip_uint32_t i = 0; i < p.num_of_dims; ++i)
    std::printf("%s%u", i ? "x" : "", p.sizes[i]);
  std::printf(" fmt=%d quant=%d", p.data_format, p.quant_format);
  if (p.quant_format == VIP_BUFFER_QUANTIZE_TF_ASYMM)
    std::printf(" scale=%g zp=%d",
                p.quant_data.affine.scale, p.quant_data.affine.zeroPoint);
  std::printf(" bytes=%zu\n", bytes);
}

void print_output(const vip_buffer_create_params_t& p,
                  const uint8_t* raw, size_t bytes) {
  size_t numel = 1;
  for (vip_uint32_t i = 0; i < p.num_of_dims; ++i) numel *= p.sizes[i];
  std::printf("output shape: {");
  for (vip_uint32_t i = 0; i < p.num_of_dims; ++i)
    std::printf("%s%u", i ? ", " : "", p.sizes[i]);
  std::printf("}, %zu elements\n", numel);
  if (numel == 0) return;

  // Dequant for summary if quant TF_ASYMM; identity if fp32; raw print
  // for anything else (matches runner_main's behavior).
  float scale = 1.0f;
  int32_t zp = 0;
  if (p.quant_format == VIP_BUFFER_QUANTIZE_TF_ASYMM) {
    scale = p.quant_data.affine.scale;
    zp = p.quant_data.affine.zeroPoint;
  }

  std::vector<float> buf(numel);
  if (p.data_format == VIP_BUFFER_FORMAT_FP32) {
    std::memcpy(buf.data(), raw, std::min(bytes, numel * sizeof(float)));
  } else if (p.data_format == VIP_BUFFER_FORMAT_INT8) {
    auto src = reinterpret_cast<const int8_t*>(raw);
    for (size_t i = 0; i < numel; ++i)
      buf[i] = (static_cast<float>(src[i]) - static_cast<float>(zp)) * scale;
  } else if (p.data_format == VIP_BUFFER_FORMAT_UINT8) {
    auto src = reinterpret_cast<const uint8_t*>(raw);
    for (size_t i = 0; i < numel; ++i)
      buf[i] = (static_cast<float>(src[i]) - static_cast<float>(zp)) * scale;
  } else {
    std::fprintf(stderr,
                 "print_output: unsupported format %d, raw bytes only.\n",
                 p.data_format);
    return;
  }

  size_t print_n = std::min(numel, kPrintFirst);
  std::printf("first %zu values (dequantized): [", print_n);
  for (size_t i = 0; i < print_n; ++i)
    std::printf("%s%.6f", i ? ", " : "", buf[i]);
  std::printf("%s]\n", numel > print_n ? ", ..." : "");

  auto max_it = std::max_element(buf.begin(), buf.end());
  auto min_it = std::min_element(buf.begin(), buf.end());
  size_t argmax = static_cast<size_t>(std::distance(buf.begin(), max_it));
  float sum = std::accumulate(buf.begin(), buf.end(), 0.0f);
  std::printf("argmax: %zu (value=%.6f)\n", argmax, *max_it);
  std::printf("min=%.6f  max=%.6f  mean=%.6f\n",
              *min_it, *max_it, sum / static_cast<float>(numel));
}

}  // namespace

int main(int argc, char** argv) {
  std::setvbuf(stdout, nullptr, _IONBF, 0);

  if (argc < 3) {
    std::fprintf(stderr,
                 "usage: %s <model.nbg> <input0.bin> [<input1.bin> ...]\n",
                 argv[0]);
    return 2;
  }
  const char* nbg_path = argv[1];
  const int input_argc = argc - 2;
  char** input_argv = argv + 2;

  using Clock = std::chrono::steady_clock;
  auto ms_since = [](Clock::time_point t0) {
    return std::chrono::duration<double, std::milli>(Clock::now() - t0).count();
  };

  // Read NBG into memory. vip_create_network can take a file path
  // directly via VIP_CREATE_NETWORK_FROM_FILE, but reading + memory
  // mode keeps the flow uniform with other vpm-style runners and
  // makes input-buffer ownership explicit.
  std::printf("[stage] reading NBG\n");
  auto nbg = read_file(nbg_path);
  std::printf("[stage] NBG size %zu bytes\n", nbg.size());

  std::printf("[stage] vip_init\n");
  auto t_init = Clock::now();
  VIP_CHECK(vip_init());
  double init_ms = ms_since(t_init);
  std::printf("[stage] vip_init done in %.2f ms\n", init_ms);

  vip_network net = nullptr;
  std::printf("[stage] vip_create_network (from memory)\n");
  auto t_create = Clock::now();
  VIP_CHECK(vip_create_network(nbg.data(),
                                static_cast<vip_uint32_t>(nbg.size()),
                                VIP_CREATE_NETWORK_FROM_MEMORY, &net),
            vip_destroy());
  double create_ms = ms_since(t_create);
  std::printf("[stage] vip_create_network done in %.2f ms\n", create_ms);

  std::printf("[stage] vip_prepare_network\n");
  auto t_prep = Clock::now();
  VIP_CHECK(vip_prepare_network(net),
            vip_destroy_network(net); vip_destroy());
  double prep_ms = ms_since(t_prep);
  std::printf("[stage] vip_prepare_network done in %.2f ms\n", prep_ms);

  vip_uint32_t input_count = 0;
  vip_uint32_t output_count = 0;
  vip_query_network(net, VIP_NETWORK_PROP_INPUT_COUNT, &input_count);
  vip_query_network(net, VIP_NETWORK_PROP_OUTPUT_COUNT, &output_count);
  std::printf("[stage] network: %u inputs, %u outputs\n",
              input_count, output_count);

  if (static_cast<vip_uint32_t>(input_argc) != input_count) {
    std::fprintf(stderr, "expected %u input file(s), got %d\n",
                 input_count, input_argc);
    vip_destroy_network(net); vip_destroy();
    return 2;
  }

  // Wire inputs.
  std::vector<vip_buffer> in_bufs(input_count, nullptr);
  std::vector<vip_buffer_create_params_t> in_params(input_count);
  std::vector<size_t> in_bytes(input_count, 0);

  for (vip_uint32_t i = 0; i < input_count; ++i) {
    in_bytes[i] = fill_io_params(net, i, /*is_input=*/true, in_params[i]);
    print_io("in", i, in_params[i], in_bytes[i]);
    VIP_CHECK(vip_create_buffer(&in_params[i], sizeof(in_params[i]),
                                  &in_bufs[i]));
    auto raw = read_file(input_argv[i]);
    if (raw.size() != in_bytes[i]) {
      std::fprintf(stderr,
                   "input %u: file %s has %zu bytes, expected %zu\n",
                   i, input_argv[i], raw.size(), in_bytes[i]);
      vip_destroy_network(net); vip_destroy();
      return 2;
    }
    void* dst = vip_map_buffer(in_bufs[i]);
    std::memcpy(dst, raw.data(), raw.size());
    vip_unmap_buffer(in_bufs[i]);
    vip_flush_buffer(in_bufs[i], VIP_BUFFER_OPER_TYPE_FLUSH);
    VIP_CHECK(vip_set_input(net, i, in_bufs[i]));
  }

  // Wire outputs.
  std::vector<vip_buffer> out_bufs(output_count, nullptr);
  std::vector<vip_buffer_create_params_t> out_params(output_count);
  std::vector<size_t> out_bytes(output_count, 0);

  for (vip_uint32_t i = 0; i < output_count; ++i) {
    out_bytes[i] = fill_io_params(net, i, /*is_input=*/false, out_params[i]);
    print_io("out", i, out_params[i], out_bytes[i]);
    VIP_CHECK(vip_create_buffer(&out_params[i], sizeof(out_params[i]),
                                  &out_bufs[i]));
    VIP_CHECK(vip_set_output(net, i, out_bufs[i]));
  }

  // Run.
  std::printf("[stage] vip_run_network\n");
  auto t_run = Clock::now();
  VIP_CHECK(vip_run_network(net));
  double run_ms = ms_since(t_run);
  std::printf("[stage] vip_run_network done in %.2f ms\n", run_ms);

  // Profile reading (NBG-internal cycle count, may be 0 if disabled).
  vip_inference_profile_t prof = {};
  if (vip_query_network(net, VIP_NETWORK_PROP_PROFILING, &prof) == VIP_SUCCESS &&
      prof.inference_time != 0) {
    std::printf("[stage] driver profile: %u us, %u cycles\n",
                prof.inference_time, prof.total_cycle);
  }

  // Read outputs.
  for (vip_uint32_t i = 0; i < output_count; ++i) {
    vip_flush_buffer(out_bufs[i], VIP_BUFFER_OPER_TYPE_INVALIDATE);
    void* src = vip_map_buffer(out_bufs[i]);
    std::vector<uint8_t> raw(out_bytes[i]);
    std::memcpy(raw.data(), src, out_bytes[i]);
    vip_unmap_buffer(out_bufs[i]);
    print_output(out_params[i], raw.data(), out_bytes[i]);
  }

  // Cleanup.
  for (auto b : in_bufs)  if (b) vip_destroy_buffer(b);
  for (auto b : out_bufs) if (b) vip_destroy_buffer(b);
  vip_finish_network(net);
  vip_destroy_network(net);
  vip_destroy();

  std::printf("[summary] init=%.2fms create=%.2fms prepare=%.2fms run=%.2fms\n",
              init_ms, create_ms, prep_ms, run_ms);
  return 0;
}
