#!/usr/bin/env python3
"""run_sample.py — feed an image into a built timvx runner.

Pipeline:
  1. decode <image.jpg> -> raw 1*H*W*3 fp32 NHWC bytes (default ImageNet-
     normalized; --no-norm emits raw [0,1]). Done in-process via PIL+numpy;
     no compiled helper needed.
  2. set LD_LIBRARY_PATH = <timvx libdir>:<sdk libdir>:$LD_LIBRARY_PATH
  3. invoke <runner> <image-input.bin>; runner stdout flows to the terminal.

This script handles the SINGLE-INPUT case (just the image blob). Runners
generated by lower_sample.py take one argv slot per non-const function arg
of the lowered model; if the source TOSA has BatchNorm tracking-parameter
args (typical from torch-mlir export), those show up too and need to be
supplied separately.

Required env (each overridable):
  REPO_ROOT          repo root              (default: parent of this script's dir)
  TIM_VX_BUILD_DIR   built TIM-VX           (default: $REPO_ROOT/TIM-VX/build/install)
  VIV_SDK_LIB_DIR    Verisilicon driver libs (libGAL.so etc.)
                     (default: $EXTERNAL_VIV_SDK/lib or
                               $HOME/ai-sdk/unified-tina/timvx-sdk/lib)
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# Standard ImageNet preprocessing constants (per RGB channel).
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD  = (0.229, 0.224, 0.225)


def find_timvx_lib_dir(tim_vx_build_dir: Path) -> Path:
    candidates = [
        tim_vx_build_dir / "install" / "lib",
        tim_vx_build_dir / "lib",
        tim_vx_build_dir / "src" / "tim",
        tim_vx_build_dir,
    ]
    for cand in candidates:
        if (cand / "libtim-vx.so").is_file():
            return cand
    sys.exit(f"could not locate libtim-vx.so under {tim_vx_build_dir}")


def decode_jpeg_to_fp32(image_path: Path, out_path: Path,
                        normalize: bool) -> tuple[int, int]:
    """Decode `image_path` and write fp32 little-endian NHWC bytes (N=1) to
    `out_path`. Returns (H, W). Raises ImportError if PIL is missing."""
    try:
        import numpy as np
        from PIL import Image
    except ImportError as e:
        sys.exit(f"missing dependency for image decode: {e}\n"
                 f"install with: pip install numpy pillow")

    # convert("RGB") forces 3-channel even for grayscale or RGBA inputs.
    img = np.asarray(Image.open(image_path).convert("RGB"),
                     dtype=np.float32) / 255.0
    if normalize:
        mean = np.array(IMAGENET_MEAN, dtype=np.float32)
        std  = np.array(IMAGENET_STD,  dtype=np.float32)
        img = (img - mean) / std

    h, w = img.shape[:2]
    # (H, W, 3) C-contiguous fp32 — same byte layout the C++ helper produced.
    np.ascontiguousarray(img, dtype=np.float32).tofile(out_path)
    return h, w


# Regex patterns for parsing the rendered runner_main.cpp's `kInputs`
# initializer. We use these to infer the input tensor's dtype, shape, and
# (scale, zp) at run time so we can write the right preprocessing — e.g.
# tflite-quantized rn50 wants raw uint8 NCHW bytes, not normalized fp32
# NHWC.
_KINPUTS_RE = re.compile(
    r"const std::vector<InputSpec> kInputs\s*=\s*\{(.*?)\};", re.S)
_INPUTSPEC_RE = re.compile(
    r"\{\s*\{([^}]+)\}\s*,\s*tim::vx::DataType::(\w+)"
    r"(?:\s*,\s*([+-]?\d+(?:\.\d*)?(?:[eE][+-]?\d+)?))?"
    r"(?:\s*,\s*(-?\d+))?\s*\}")


def parse_kinputs(runner_cpp: Path) -> list[dict]:
    """Inspect the rendered runner_main.cpp's `kInputs` initializer and
    return a list of {shape, dtype, quant_scale, quant_zp} dicts — one
    per tensor input the runner expects. Used to drive input-image
    preprocessing (uint8 vs fp32, NCHW vs NHWC layout, etc.)."""
    if not runner_cpp.is_file():
        return []
    text = runner_cpp.read_text()
    block = _KINPUTS_RE.search(text)
    if not block:
        return []
    specs = []
    for m in _INPUTSPEC_RE.finditer(block.group(1)):
        shape = [int(s.strip()) for s in m.group(1).split(",") if s.strip()]
        specs.append({
            "shape": shape,
            "dtype": m.group(2),
            "quant_scale": float(m.group(3)) if m.group(3) else 0.0,
            "quant_zp": int(m.group(4)) if m.group(4) else 0,
        })
    return specs


def decode_jpeg_for_spec(image_path: Path, out_path: Path,
                         spec: dict, normalize: bool) -> tuple[int, int]:
    """Decode `image_path` and write bytes matching `spec` (parsed from
    the runner's kInputs). Picks the right dtype + layout per spec:

      * Float dtypes (FLOAT32 / FLOAT16): fp32 NHWC bytes, optionally
        ImageNet-normalised. Mirrors the original behaviour.
      * Integer dtypes (UINT8 / INT8): raw image bytes in the layout the
        runner declared. NCHW for `[N, C=3, H, W]`-shaped inputs (the
        typical tflite quantized vision model), NHWC for `[N, H, W, C=3]`.
        No normalisation — the model carries the (scale, zp) it was
        calibrated for, so the runner's tensor reads raw bytes directly
        and dequantises via Quantization() at the kernel layer.
    """
    try:
        import numpy as np
        from PIL import Image
    except ImportError as e:
        sys.exit(f"missing dependency for image decode: {e}\n"
                 f"install with: pip install numpy pillow")

    shape = spec["shape"]
    dtype = spec["dtype"]
    if len(shape) != 4:
        sys.exit(f"unsupported input rank {len(shape)} for image decode "
                 f"(spec shape={shape})")

    # Detect NCHW vs NHWC by which non-N dim is 3 (the colour channel).
    # Falls back to NHWC for ambiguous cases (e.g. shape (1, 1, 1, 3)).
    if shape[1] == 3 and shape[2] != 3:
        layout = "NCHW"
        h, w = shape[2], shape[3]
    else:
        layout = "NHWC"
        h, w = shape[1], shape[2]

    img = Image.open(image_path).convert("RGB").resize((w, h))

    if dtype in ("FLOAT32", "FLOAT16"):
        arr = np.asarray(img, dtype=np.float32) / 255.0
        if normalize:
            mean = np.array(IMAGENET_MEAN, dtype=np.float32)
            std  = np.array(IMAGENET_STD,  dtype=np.float32)
            arr = (arr - mean) / std
        if layout == "NCHW":
            arr = arr.transpose(2, 0, 1)  # HWC -> CHW
        np.ascontiguousarray(arr, dtype=np.float32).tofile(out_path)
    else:
        # Integer dtypes — feed raw image bytes; the runner's
        # Quantization(scale, zp) handles the dequant at op time.
        arr = np.asarray(img, dtype=np.uint8)
        if layout == "NCHW":
            arr = arr.transpose(2, 0, 1)
        if dtype == "INT8":
            # If the runner declared INT8, store as signed; the harness
            # below is responsible for the i8↔u8 byte semantics. Most
            # tflite quantized models with i8 storage in MLIR get
            # i8→u8 promoted by lower_to_timvx.py and end up as UINT8
            # here.
            arr = (arr.astype(np.int16) - 128).astype(np.int8)
        np.ascontiguousarray(arr).tofile(out_path)
    return h, w


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("runner", type=Path,
                    help="Path to the timvx runner binary "
                         "(e.g. lower_out/<name>/<name>_runner)")
    ap.add_argument("image", type=Path, nargs="?", default=None,
                    help="Image to feed in (default: debug_scripts/cat105.jpg)")
    ap.add_argument("--no-norm", action="store_true",
                    help="Skip ImageNet mean/std normalization (emit raw [0,1])")
    ap.add_argument("--keep", action="store_true",
                    help="Keep the temp .bin input file (path printed to stderr)")
    args = ap.parse_args()

    if not args.runner.is_file() or not os.access(args.runner, os.X_OK):
        sys.exit(f"not executable: {args.runner}")

    script_dir = Path(__file__).resolve().parent
    repo_root = Path(os.environ.get("REPO_ROOT", script_dir.parent)).resolve()

    image = args.image or (script_dir / "cat105.jpg")
    if not image.is_file():
        sys.exit(f"image not found: {image}")

    tim_vx_build_dir = Path(os.environ.get(
        "TIM_VX_BUILD_DIR", repo_root / "TIM-VX" / "build" / "install"))
    default_sdk = (Path(os.environ.get("EXTERNAL_VIV_SDK",
                       Path.home() / "ufs" / "home" / "radxa" / "ai-sdk" / "unified-tina" / "timvx-sdk"))
                   / "lib")
    viv_sdk_lib_dir = Path(os.environ.get("VIV_SDK_LIB_DIR", default_sdk))

    timvx_lib_dir = find_timvx_lib_dir(tim_vx_build_dir)
    if not viv_sdk_lib_dir.is_dir():
        sys.exit(f"VIV_SDK_LIB_DIR does not exist: {viv_sdk_lib_dir}")

    # libCLC's JIT EVIS / CL shader compiler resolves
    # `#include "cl_viv_vx_ext.h"` against `$VIVANTE_SDK_DIR/include/CL/`.
    # The runtime unified-tina SDK doesn't ship that header, but TIM-VX's
    # prebuilt-sdk does — bundle it into a shim dir we point
    # VIVANTE_SDK_DIR at when launching the runner. Anything that lowers
    # a `tosa.cast` (now via tim::vx::ops::Cast) hits this path —
    # without the shim the kernel JIT fails with "Cannot find the header
    # file cl_viv_vx_ext.h". Idempotent.
    viv_shim = script_dir / ".build" / "viv_sdk_shim"
    viv_prebuilt_header = (repo_root / "TIM-VX" / "prebuilt-sdk" /
                           "x86_64_linux" / "include" / "CL" /
                           "cl_viv_vx_ext.h")
    target_header = viv_shim / "include" / "CL" / "cl_viv_vx_ext.h"
    if not target_header.is_file():
        if not viv_prebuilt_header.is_file():
            sys.exit(f"prebuilt-sdk header missing: {viv_prebuilt_header}\n"
                     f"  the EVIS shader compiler needs cl_viv_vx_ext.h "
                     f"to JIT cast/elementwise kernels.")
        target_header.parent.mkdir(parents=True, exist_ok=True)
        target_header.write_bytes(viv_prebuilt_header.read_bytes())

    # Decode → temp file. tempfile.mkstemp returns (fd, path); close fd so
    # numpy.tofile can open the path itself.
    fd, raw = tempfile.mkstemp(prefix="timvx-input-", suffix=".bin", dir="/tmp")
    os.close(fd)
    input_bin = Path(raw)

    try:
        # Inspect the runner's compiled-in kInputs to pick the right
        # preprocessing for this model. The runner is built next to its
        # rendered runner_main.cpp; if the cpp isn't present we fall back
        # to the legacy fp32 NHWC path.
        runner_cpp = args.runner.parent / "runner_main.cpp"
        specs = parse_kinputs(runner_cpp)
        if specs and len(specs) == 1:
            spec = specs[0]
            h, w = decode_jpeg_for_spec(image, input_bin, spec,
                                          normalize=not args.no_norm)
            print(f"wrote {input_bin.stat().st_size} bytes "
                  f"(shape={spec['shape']}, dtype={spec['dtype']}, "
                  f"quant_scale={spec['quant_scale']}, "
                  f"quant_zp={spec['quant_zp']}) -> {input_bin}",
                  file=sys.stderr)
        else:
            h, w = decode_jpeg_to_fp32(image, input_bin,
                                        normalize=not args.no_norm)
            kind = "[0,1]" if args.no_norm else "imagenet-normalized"
            print(f"wrote {h*w*3} fp32 ({h}x{w}x3 NHWC, batch=1, {kind}) -> {input_bin}",
                  file=sys.stderr)

        if args.keep:
            print(f"input bin (kept): {input_bin}", file=sys.stderr)

        ld_path = os.pathsep.join(filter(None, [
            str(timvx_lib_dir),
            str(viv_sdk_lib_dir),
            os.environ.get("LD_LIBRARY_PATH", ""),
        ]))
        env = {**os.environ,
               "LD_LIBRARY_PATH": ld_path,
               "VIVANTE_SDK_DIR": str(viv_shim),
               "VSI_NN_LOG_LEVEL": str(5)}

        print("---", file=sys.stderr)
        print(f"running {args.runner} {input_bin}", file=sys.stderr)
        print(f"  LD_LIBRARY_PATH += {timvx_lib_dir}:{viv_sdk_lib_dir}",
              file=sys.stderr)
        print(f"  VIVANTE_SDK_DIR  = {viv_shim}", file=sys.stderr)
        print("---", file=sys.stderr)

        import time
        t0 = time.monotonic()
        result = subprocess.run([str(args.runner), str(input_bin)], env=env)
        elapsed = time.monotonic() - t0
        # Surface exit code + signal info so a silent crash (typical
        # libGAL / OVXLIB abort path: SIGSEGV inside the kernel JIT, or
        # an internal exit() call) doesn't look like a clean termination.
        # A negative returncode in subprocess.run means the process was
        # killed by signal -returncode (e.g. -11 = SIGSEGV).
        if result.returncode < 0:
            import signal
            try:
                sig_name = signal.Signals(-result.returncode).name
            except (ValueError, AttributeError):
                sig_name = f"signal {-result.returncode}"
            print(f"[run_sample] runner killed by {sig_name} after "
                  f"{elapsed:.2f}s", file=sys.stderr)
        else:
            print(f"[run_sample] runner exited rc={result.returncode} "
                  f"after {elapsed:.2f}s", file=sys.stderr)
        return result.returncode
    finally:
        if not args.keep:
            input_bin.unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(main())
