// runner_main.cpp — auto-generated by lower_sample.bash. Edits welcome,
// the next regeneration will overwrite. The script substitutes four
// markers (BASE, FUNC_NAME, INPUT_SPECS, INPUT_ARGS) at the appropriate
// places below. See the kInputs initializer and the call-site to spot
// what was generated.
//
// Default behavior:
//   1. argv[1..N] are paths to raw binary blobs, one per non-const
//      function argument (image input plus any args the source MLIR
//      didn't fold into tosa.const — typical case is BatchNorm running
//      stats from frontends like torch-mlir). Element types match the
//      MLIR signature (parsed at lowering time into the kInputs init below).
//   2. Construct a tim::vx::Graph; build N INPUT tensors with the
//      configured shapes; copy each blob into its tensor.
//   3. Call __FUNC_NAME__(graph, inputs[0], ..., inputs[N-1]).
//      tosa.const data is already baked into the lowered function as
//      static arrays — no separate weights file needed. The lowering
//      pass also marks the func.return tensor as TensorAttribute::OUTPUT
//      so it can be read back via CopyDataFromTensor after Run().
//   4. Compile() + Run(); print output shape, first values, argmax,
//      min/max/mean to stdout.

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iterator>
#include <memory>
#include <numeric>
#include <vector>

#include "tim/vx/context.h"
#include "tim/vx/graph.h"
#include "tim/vx/tensor.h"
#include "tim/vx/types.h"

#include "timvx_runtime.h"
#include "__BASE__.func.cpp"

namespace {

struct InputSpec {
  std::vector<uint32_t> shape;
  tim::vx::DataType     dtype;
  // For quantized models: the (scale, zp) the network was calibrated for.
  // Set to (0.0, 0) to mean "no quant" — the runner skips Quantization()
  // on the spec in that case.
  double  quant_scale = 0.0;
  int32_t quant_zp    = 0;
};

// Parsed from the timvx MLIR's function signature; one entry per non-graph
// argument, in declaration order. To override (e.g. for a non-FP32 model),
// regenerate this file or hand-edit.
const std::vector<InputSpec> kInputs = {
__INPUT_SPECS__
};

constexpr size_t kPrintFirst = 16;

std::vector<uint8_t> read_file(const char* path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) {
    std::fprintf(stderr, "cannot open input: %s\n", path);
    std::exit(1);
  }
  std::streamsize n = f.tellg();
  f.seekg(0, std::ios::beg);
  std::vector<uint8_t> buf(static_cast<size_t>(n));
  f.read(reinterpret_cast<char*>(buf.data()), n);
  return buf;
}

// Element size in bytes for each TIM-VX dtype the runner cares about.
inline size_t bytesPerElem(tim::vx::DataType dt) {
  switch (dt) {
    case tim::vx::DataType::FLOAT16:
    case tim::vx::DataType::INT16:
    case tim::vx::DataType::UINT16: return 2;
    case tim::vx::DataType::INT8:
    case tim::vx::DataType::UINT8:
    case tim::vx::DataType::BOOL8:  return 1;
    case tim::vx::DataType::INT64:  return 8;
    default:                         return 4;  // FLOAT32 / INT32 / UINT32
  }
}

// Layout-convert bytes between MLIR row-major (rightmost dim is in-memory
// innermost) and TIM-VX innermost-first (leftmost dim of the shape vector
// is in-memory innermost), preserving the (i_0, ..., i_{R-1}) coord-to-
// value mapping. The two byte layouts differ for any shape with two or
// more non-trivial dims that aren't symmetrically arranged.
//
// Why this exists: the harness reads input.bin written by a Python
// preprocess that outputs MLIR row-major bytes (W rightmost = innermost in
// memory for NCHW). TIM-VX's transpose / conv / pool ops walk bytes per
// the innermost-first convention. Without this conversion the MLIR ops'
// output bytes are scrambled relative to MLIR semantics for any model
// with non-palindromic shapes (the C=3 issue we hit with simple_v1).
//
// Doing this AT THE HARNESS BOUNDARY means the entire MLIR pipeline can
// stay innocent of the convention mismatch — internal bytes are
// uniformly TIM-VX-innermost-first, op_tests stay correct, and only
// runner_main.cpp.tpl knows about the layout flip.
inline void layoutConvert(const uint8_t* src, uint8_t* dst,
                           const std::vector<uint32_t>& shape,
                           size_t elem_size, bool from_mlir_to_tvx) {
  size_t rank = shape.size();
  size_t numel = 1;
  for (auto d : shape) numel *= d;
  if (rank <= 1) {
    std::memcpy(dst, src, numel * elem_size);
    return;
  }
  // mlir_strides[k] = product(shape[k+1..rank))  — rightmost is fastest.
  // tvx_strides[k]  = product(shape[0..k))       — leftmost is fastest.
  std::vector<size_t> mlir_strides(rank), tvx_strides(rank);
  mlir_strides[rank - 1] = 1;
  for (int k = static_cast<int>(rank) - 2; k >= 0; --k)
    mlir_strides[k] = mlir_strides[k + 1] * shape[k + 1];
  tvx_strides[0] = 1;
  for (size_t k = 1; k < rank; ++k)
    tvx_strides[k] = tvx_strides[k - 1] * shape[k - 1];

  std::vector<size_t> idx(rank, 0);
  for (size_t e = 0; e < numel; ++e) {
    size_t mlir_off = 0, tvx_off = 0;
    for (size_t k = 0; k < rank; ++k) {
      mlir_off += idx[k] * mlir_strides[k];
      tvx_off  += idx[k] * tvx_strides[k];
    }
    if (from_mlir_to_tvx) {
      std::memcpy(dst + tvx_off * elem_size,
                  src + mlir_off * elem_size, elem_size);
    } else {
      std::memcpy(dst + mlir_off * elem_size,
                  src + tvx_off * elem_size, elem_size);
    }
    // Iterate idx in MLIR row-major order (least-significant first).
    for (int k = static_cast<int>(rank) - 1; k >= 0; --k) {
      if (++idx[k] < shape[k]) break;
      idx[k] = 0;
    }
  }
}

void print_output(const std::shared_ptr<tim::vx::Tensor>& t) {
  const auto& shape = t->GetShape();
  size_t numel = 1;
  for (auto d : shape) numel *= d;

  std::printf("output shape: {");
  for (size_t i = 0; i < shape.size(); ++i)
    std::printf("%s%u", i ? ", " : "", shape[i]);
  std::printf("}, %zu elements\n", numel);
  if (numel == 0) return;

  // Read in the tensor's actual storage type, then dequantize / convert to
  // float for human-friendly summary stats. Quant info on the tensor's
  // spec gives us (scale, zp); for unquantized outputs we treat it as
  // identity.
  auto dtype = t->GetDataType();
  auto quant = t->GetQuantization();
  float scale = 1.0f;
  int32_t zp = 0;
  if (quant.Type() != tim::vx::QuantType::NONE && !quant.Scales().empty()) {
    scale = quant.Scales()[0];
    if (!quant.ZeroPoints().empty()) zp = quant.ZeroPoints()[0];
  }

  // Read raw TIM-VX-innermost-first bytes, then convert back to MLIR
  // row-major so the summary (argmax index, first-N values) lines up
  // with what CPU's MLIR-row-major output produces.
  size_t elem = bytesPerElem(dtype);
  std::vector<uint8_t> tvx_bytes(numel * elem);
  if (!t->CopyDataFromTensor(tvx_bytes.data())) {
    std::fprintf(stderr, "CopyDataFromTensor failed\n"); std::exit(3);
  }
  std::vector<uint8_t> mlir_bytes(numel * elem);
  layoutConvert(tvx_bytes.data(), mlir_bytes.data(), shape, elem,
                /*from_mlir_to_tvx=*/false);

  std::vector<float> buf(numel);
  if (dtype == tim::vx::DataType::FLOAT32) {
    std::memcpy(buf.data(), mlir_bytes.data(), numel * sizeof(float));
  } else if (dtype == tim::vx::DataType::INT8) {
    auto* raw = reinterpret_cast<const int8_t*>(mlir_bytes.data());
    for (size_t i = 0; i < numel; ++i)
      buf[i] = (static_cast<float>(raw[i]) - static_cast<float>(zp)) * scale;
  } else if (dtype == tim::vx::DataType::UINT8) {
    auto* raw = mlir_bytes.data();
    for (size_t i = 0; i < numel; ++i)
      buf[i] = (static_cast<float>(raw[i]) - static_cast<float>(zp)) * scale;
  } else {
    std::fprintf(stderr,
                 "print_output: unsupported dtype %d; raw bytes only.\n",
                 static_cast<int>(dtype));
    return;
  }

  size_t print_n = std::min(numel, kPrintFirst);
  std::printf("first %zu values (dequantized): [", print_n);
  for (size_t i = 0; i < print_n; ++i)
    std::printf("%s%.6f", i ? ", " : "", buf[i]);
  std::printf("%s]\n", numel > print_n ? ", ..." : "");

  auto max_it = std::max_element(buf.begin(), buf.end());
  auto min_it = std::min_element(buf.begin(), buf.end());
  size_t argmax = static_cast<size_t>(std::distance(buf.begin(), max_it));
  float sum = std::accumulate(buf.begin(), buf.end(), 0.0f);
  std::printf("argmax: %zu (value=%.6f)\n", argmax, *max_it);
  std::printf("min=%.6f  max=%.6f  mean=%.6f\n",
              *min_it, *max_it, sum / static_cast<float>(numel));
}

}  // namespace

int main(int argc, char** argv) {
  // Disable stdout buffering. When the runner is launched as a child of
  // run_sample.py (subprocess.run with no PIPE), stdout is fully
  // buffered if it points at anything other than a TTY — and libGAL /
  // OVXLIB writes go to stderr, so a process abort mid-way can lose all
  // of our buffered diagnostic output. Make stdout unbuffered so each
  // [stage] line appears immediately.
  std::setvbuf(stdout, nullptr, _IONBF, 0);

  if (argc != static_cast<int>(kInputs.size()) + 1) {
    std::fprintf(stderr, "usage: %s", argv[0]);
    for (size_t i = 0; i < kInputs.size(); ++i)
      std::fprintf(stderr, " <input%zu.bin>", i);
    std::fprintf(stderr,
                 "\n  expected %zu raw-binary inputs, one per non-graph "
                 "function argument.\n",
                 kInputs.size());
    return 2;
  }

  auto ctx = tim::vx::Context::Create();
  if (!ctx) { std::fprintf(stderr, "Context::Create failed\n"); return 1; }

  auto graph = ctx->CreateGraph();
  if (!graph) { std::fprintf(stderr, "ctx->CreateGraph failed\n"); return 1; }

  // Read input file bytes upfront, but DEFER CopyDataToTensor until AFTER
  // graph->Compile(). The TIM-VX samples (e.g. lenet_asymu8.cc) establish
  // this order: build graph → Compile() → CopyDataToTensor → Run(). Doing
  // the copy before Compile leaves INPUT tensors with no live data after
  // Compile reorganises the graph — the model then sees a constant
  // (typically all-zero) input and produces input-independent output.
  std::vector<std::shared_ptr<tim::vx::Tensor>> inputs;
  std::vector<std::vector<uint8_t>> input_blobs;
  inputs.reserve(kInputs.size());
  input_blobs.reserve(kInputs.size());
  for (size_t i = 0; i < kInputs.size(); ++i) {
    input_blobs.push_back(read_file(argv[i + 1]));
    auto spec = (kInputs[i].quant_scale != 0.0)
        ? tim::vx::TensorSpec(
              kInputs[i].dtype, kInputs[i].shape,
              tim::vx::TensorAttribute::INPUT,
              tim::vx::Quantization(tim::vx::QuantType::ASYMMETRIC,
                                     static_cast<float>(kInputs[i].quant_scale),
                                     kInputs[i].quant_zp))
        : tim::vx::TensorSpec(kInputs[i].dtype, kInputs[i].shape,
                              tim::vx::TensorAttribute::INPUT);
    inputs.push_back(graph->CreateTensor(spec));
  }

  // Stage markers + timing. We flush after every print because libGAL
  // and the OVXLIB log layer can reorder buffered output otherwise; if
  // `Compile()` aborts mid-way, an unflushed "[stage] compiling" line
  // can be lost. Wall-clock is fine for an order-of-magnitude read.
  using Clock = std::chrono::steady_clock;
  auto ms_since = [](Clock::time_point t0) {
    return std::chrono::duration<double, std::milli>(Clock::now() - t0).count();
  };

  // Cheap peak-RSS sampler. Compile-time memory usage by libCLC / the
  // EVIS shader cache can spike non-monotonically — a leaky JIT path
  // shows up as the per-stage delta blowing past expected runtime
  // tensor sizes. Reads /proc/self/status' VmHWM line (high-water mark).
  auto rss_kb = []() -> long {
    std::ifstream f("/proc/self/status");
    std::string line;
    while (std::getline(f, line))
      if (line.rfind("VmHWM:", 0) == 0)
        return std::strtol(line.c_str() + 6, nullptr, 10);
    return -1;
  };
  auto stage = [&](const char* tag, double ms) {
    long rss = rss_kb();
    if (rss >= 0)
      std::printf("[stage] %s in %.2f ms (peak RSS %.1f MiB)\n",
                  tag, ms, rss / 1024.0);
    else
      std::printf("[stage] %s in %.2f ms\n", tag, ms);
    std::fflush(stdout);
  };

  std::printf("[stage] building graph\n"); std::fflush(stdout);
  auto t_build = Clock::now();
  auto output = __FUNC_NAME__(graph, __INPUT_ARGS__);
  double build_ms = ms_since(t_build);
  stage("graph built", build_ms);

  std::printf("[stage] compiling\n"); std::fflush(stdout);
  auto t_compile = Clock::now();
  if (!graph->Compile()) {
    std::fprintf(stderr, "graph->Compile failed\n");
    return 3;
  }
  double compile_ms = ms_since(t_compile);
  stage("compile done", compile_ms);

  // Now (post-Compile) wire input bytes into the input tensors. See the
  // note above kInputs/blobs initialization for why this is deferred.
  // We layout-convert MLIR row-major bytes from input.bin to the
  // TIM-VX innermost-first layout that internal ops walk in.
  for (size_t i = 0; i < inputs.size(); ++i) {
    size_t elem = bytesPerElem(kInputs[i].dtype);
    std::vector<uint8_t> tvx_bytes(input_blobs[i].size());
    layoutConvert(input_blobs[i].data(), tvx_bytes.data(),
                  kInputs[i].shape, elem, /*from_mlir_to_tvx=*/true);
    if (!inputs[i]->CopyDataToTensor(
            tvx_bytes.data(),
            static_cast<uint32_t>(tvx_bytes.size()))) {
      std::fprintf(stderr,
                   "CopyDataToTensor failed for input %zu (%zu bytes)\n",
                   i, tvx_bytes.size());
      return 3;
    }
  }

  std::printf("[stage] running inference\n"); std::fflush(stdout);
  auto t_run = Clock::now();
  if (!graph->Run()) {
    std::fprintf(stderr, "graph->Run failed after %.2f ms\n", ms_since(t_run));
    std::fflush(stderr);
    // Skip the C++ destructor chain. tim::vx::Context / Graph dtors
    // block on libGAL command-queue teardown, and a failed Run() can
    // leave commands in flight that the dtor never reaps — observed
    // hang requiring two Ctrl+C's. _exit bypasses cleanup; the kernel
    // reaps the GPU FDs.
    std::_Exit(3);
  }
  double run_ms = ms_since(t_run);
  stage("run done", run_ms);

  print_output(output);
  std::fflush(stdout);

  std::printf("[summary] build=%.2fms compile=%.2fms run=%.2fms\n",
              build_ms, compile_ms, run_ms);
  std::fflush(stdout);
  return 0;
}
