#!/usr/bin/env python3
"""run_sample.py — feed an image into a built timvx runner.

Pipeline:
  1. decode <image.jpg> -> raw 1*H*W*3 fp32 NHWC bytes (default ImageNet-
     normalized; --no-norm emits raw [0,1]). Done in-process via PIL+numpy;
     no compiled helper needed.
  2. set LD_LIBRARY_PATH = <timvx libdir>:<sdk libdir>:$LD_LIBRARY_PATH
  3. invoke <runner> <image-input.bin>; runner stdout flows to the terminal.

This script handles the SINGLE-INPUT case (just the image blob). Runners
generated by lower_sample.py take one argv slot per non-const function arg
of the lowered model; if the source TOSA has BatchNorm tracking-parameter
args (typical from torch-mlir export), those show up too and need to be
supplied separately.

Required env (each overridable):
  REPO_ROOT          repo root              (default: parent of this script's dir)
  TIM_VX_BUILD_DIR   built TIM-VX           (default: $REPO_ROOT/TIM-VX/build/install)
  VIV_SDK_LIB_DIR    Verisilicon driver libs (libGAL.so etc.)
                     (default: $EXTERNAL_VIV_SDK/lib or
                               $HOME/ai-sdk/unified-tina/timvx-sdk/lib)
"""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# Standard ImageNet preprocessing constants (per RGB channel).
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD  = (0.229, 0.224, 0.225)


def find_timvx_lib_dir(tim_vx_build_dir: Path) -> Path:
    candidates = [
        tim_vx_build_dir / "install" / "lib",
        tim_vx_build_dir / "lib",
        tim_vx_build_dir / "src" / "tim",
        tim_vx_build_dir,
    ]
    for cand in candidates:
        if (cand / "libtim-vx.so").is_file():
            return cand
    sys.exit(f"could not locate libtim-vx.so under {tim_vx_build_dir}")


def decode_jpeg_to_fp32(image_path: Path, out_path: Path,
                        normalize: bool) -> tuple[int, int]:
    """Decode `image_path` and write fp32 little-endian NHWC bytes (N=1) to
    `out_path`. Returns (H, W). Raises ImportError if PIL is missing."""
    try:
        import numpy as np
        from PIL import Image
    except ImportError as e:
        sys.exit(f"missing dependency for image decode: {e}\n"
                 f"install with: pip install numpy pillow")

    # convert("RGB") forces 3-channel even for grayscale or RGBA inputs.
    img = np.asarray(Image.open(image_path).convert("RGB"),
                     dtype=np.float32) / 255.0
    if normalize:
        mean = np.array(IMAGENET_MEAN, dtype=np.float32)
        std  = np.array(IMAGENET_STD,  dtype=np.float32)
        img = (img - mean) / std

    h, w = img.shape[:2]
    # (H, W, 3) C-contiguous fp32 — same byte layout the C++ helper produced.
    np.ascontiguousarray(img, dtype=np.float32).tofile(out_path)
    return h, w


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("runner", type=Path,
                    help="Path to the timvx runner binary "
                         "(e.g. lower_out/<name>/<name>_runner)")
    ap.add_argument("image", type=Path, nargs="?", default=None,
                    help="Image to feed in (default: debug_scripts/cat105.jpg)")
    ap.add_argument("--no-norm", action="store_true",
                    help="Skip ImageNet mean/std normalization (emit raw [0,1])")
    ap.add_argument("--keep", action="store_true",
                    help="Keep the temp .bin input file (path printed to stderr)")
    args = ap.parse_args()

    if not args.runner.is_file() or not os.access(args.runner, os.X_OK):
        sys.exit(f"not executable: {args.runner}")

    script_dir = Path(__file__).resolve().parent
    repo_root = Path(os.environ.get("REPO_ROOT", script_dir.parent)).resolve()

    image = args.image or (script_dir / "cat105.jpg")
    if not image.is_file():
        sys.exit(f"image not found: {image}")

    tim_vx_build_dir = Path(os.environ.get(
        "TIM_VX_BUILD_DIR", repo_root / "TIM-VX" / "build" / "install"))
    default_sdk = (Path(os.environ.get("EXTERNAL_VIV_SDK",
                       Path.home() / "ufs" / "home" / "radxa" / "ai-sdk" / "unified-tina" / "timvx-sdk"))
                   / "lib")
    viv_sdk_lib_dir = Path(os.environ.get("VIV_SDK_LIB_DIR", default_sdk))

    timvx_lib_dir = find_timvx_lib_dir(tim_vx_build_dir)
    if not viv_sdk_lib_dir.is_dir():
        sys.exit(f"VIV_SDK_LIB_DIR does not exist: {viv_sdk_lib_dir}")

    # Decode → temp file. tempfile.mkstemp returns (fd, path); close fd so
    # numpy.tofile can open the path itself.
    fd, raw = tempfile.mkstemp(prefix="timvx-input-", suffix=".bin", dir="/tmp")
    os.close(fd)
    input_bin = Path(raw)

    try:
        h, w = decode_jpeg_to_fp32(image, input_bin, normalize=not args.no_norm)
        kind = "[0,1]" if args.no_norm else "imagenet-normalized"
        print(f"wrote {h*w*3} fp32 ({h}x{w}x3 NHWC, batch=1, {kind}) -> {input_bin}",
              file=sys.stderr)

        if args.keep:
            print(f"input bin (kept): {input_bin}", file=sys.stderr)

        ld_path = os.pathsep.join(filter(None, [
            str(timvx_lib_dir),
            str(viv_sdk_lib_dir),
            os.environ.get("LD_LIBRARY_PATH", ""),
        ]))
        env = {**os.environ, "LD_LIBRARY_PATH": ld_path}

        print("---", file=sys.stderr)
        print(f"running {args.runner} {input_bin}", file=sys.stderr)
        print(f"  LD_LIBRARY_PATH += {timvx_lib_dir}:{viv_sdk_lib_dir}",
              file=sys.stderr)
        print("---", file=sys.stderr)

        result = subprocess.run([str(args.runner), str(input_bin)], env=env)
        return result.returncode
    finally:
        if not args.keep:
            input_bin.unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(main())
