#!/usr/bin/env bash
#
# run_sample.bash — preprocess an image and feed it into a built timvx
# runner, with the right LD_LIBRARY_PATH so the dynamic libs resolve.
#
# Pipeline:
#   1. ensure jpeg_to_raw + glibc compat shim helpers are built, and a
#      patched mirror of the Verisilicon SDK lib dir exists.
#      patch_libgal.bash from radxa_a733_scripts handles the libGAL.so
#      rewrite; see radxa_a733_scripts/README.md for the rationale.
#   2. decode <image.jpg> -> raw 1xHxWx3 fp32 NHWC bytes (default
#      ImageNet-normalized; use --no-norm for [0,1]).
#   3. set LD_LIBRARY_PATH = <timvx libdir>:<patched sdk libdir>:$LD_LIBRARY_PATH
#      and LD_PRELOAD the glibc compat shim.
#   4. invoke <runner> <image-input.bin>; whatever the runner writes to
#      stdout is forwarded directly so model output prints in the terminal.
#
# This script handles the SINGLE-INPUT case (just the cat105.jpg blob).
# Runners generated by lower_sample.bash take one argv slot per non-const
# function arg of the lowered model; if the source TOSA has BatchNorm /
# other tracking-parameter args (typical from torch-mlir export), those
# show up too and need to be supplied separately.

set -euo pipefail

###############################################################################
# CLI
###############################################################################

usage() {
  cat <<EOF
Usage: $(basename "$0") [options] <runner> [image.jpg]

Positional:
  runner       path to the timvx runner binary (e.g. lower_out/<name>/<name>_runner)
  image.jpg    image to feed in (default: debug_scripts/cat105.jpg)

Options:
  --no-norm    skip ImageNet mean/std normalization (emit raw [0,1] floats)
  --keep       keep the temp .bin input file (printed to stderr)
  -h, --help   this help

Env (each can be overridden):
  REPO_ROOT          repo root (default: parent of this script's dir)
  TIM_VX_BUILD_DIR   built TIM-VX (libtim-vx.so + headers).
                     default: \$REPO_ROOT/TIM-VX/build/install
  VIV_SDK_LIB_DIR    Verisilicon driver libs (libGAL.so etc.).
                     default: \$EXTERNAL_VIV_SDK/lib or
                              \$HOME/ai-sdk/unified-tina/timvx-sdk/lib
  CXX                C++ compiler used to build jpeg_to_raw helper
                     (default: clang++-16, then clang++)
EOF
}

no_norm=0
keep_input=0
runner=""
image=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-norm)  no_norm=1; shift ;;
    --keep)     keep_input=1; shift ;;
    -h|--help)  usage; exit 0 ;;
    -*)         echo "unknown flag: $1" >&2; usage >&2; exit 2 ;;
    *)          if   [[ -z "$runner" ]]; then runner="$1"
                elif [[ -z "$image"  ]]; then image="$1"
                else echo "unexpected positional: $1" >&2; exit 2; fi
                shift ;;
  esac
done

[[ -n "$runner" ]] || { usage >&2; exit 2; }
[[ -x "$runner" ]] || { echo "not executable: $runner" >&2; exit 1; }

###############################################################################
# Paths
###############################################################################

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$script_dir/.." && pwd)}"
image="${image:-$script_dir/cat105.jpg}"
[[ -f "$image" ]] || { echo "image not found: $image" >&2; exit 1; }

TIM_VX_BUILD_DIR="${TIM_VX_BUILD_DIR:-$REPO_ROOT/TIM-VX/build/install}"
VIV_SDK_LIB_DIR="${VIV_SDK_LIB_DIR:-${EXTERNAL_VIV_SDK:-$HOME/ai-sdk/unified-tina/timvx-sdk}/lib}"

# Find libtim-vx.so under TIM_VX_BUILD_DIR — same probe order as lower_sample.bash.
timvx_lib_dir=""
for c in "$TIM_VX_BUILD_DIR/install/lib" "$TIM_VX_BUILD_DIR/lib" \
         "$TIM_VX_BUILD_DIR/src/tim" "$TIM_VX_BUILD_DIR"; do
  if [[ -f "$c/libtim-vx.so" ]]; then timvx_lib_dir="$c"; break; fi
done
[[ -n "$timvx_lib_dir" ]] || { echo "could not locate libtim-vx.so under $TIM_VX_BUILD_DIR" >&2; exit 1; }
[[ -d "$VIV_SDK_LIB_DIR" ]] || { echo "VIV_SDK_LIB_DIR does not exist: $VIV_SDK_LIB_DIR" >&2; exit 1; }

###############################################################################
# Helper: jpeg_to_raw (decode JPEG -> NHWC fp32)
###############################################################################

setup_dir="$REPO_ROOT/radxa_a733_scripts"
helper_src="$script_dir/jpeg_to_raw.cpp"
helper_bin="$script_dir/.build/jpeg_to_raw"
shim_src="$setup_dir/glibc_compat_shim.c"
shim_so="$script_dir/.build/libtimvx_glibc_compat.so"
patched_sdk_dir="$script_dir/.build/viv-sdk-patched"
mkdir -p "$script_dir/.build"

CXX="${CXX:-}"
CC="${CC:-}"
if [[ -z "$CXX" ]]; then
  if command -v clang++-16 >/dev/null; then CXX=clang++-16
  else CXX=clang++; fi
fi
if [[ -z "$CC" ]]; then
  if command -v clang-16 >/dev/null; then CC=clang-16
  else CC=clang; fi
fi

if [[ ! -x "$helper_bin" || "$helper_src" -nt "$helper_bin" ]]; then
  echo "[build] $CXX $helper_src -> $helper_bin" >&2
  "$CXX" -std=c++17 -O2 "$helper_src" -ljpeg -o "$helper_bin"
fi

# glibc compat shim — see $setup_dir/glibc_compat_shim.c. Plain unversioned
# exports of stat/lstat/fstat that forward to __xstat etc.; LD_PRELOADed at
# the end so libGAL.so's @GLIBC_2.33-stripped references resolve.
if [[ ! -e "$shim_so" || "$shim_src" -nt "$shim_so" ]]; then
  echo "[build] $CC $shim_src -> $shim_so" >&2
  "$CC" -shared -fPIC -O2 "$shim_src" -o "$shim_so"
fi

# Patched mirror of the Verisilicon SDK lib dir. Everything is symlinked
# back to the real SDK except libGAL.so, which is copied and patched via
# radxa_a733_scripts/patch_libgal.bash (clears @GLIBC_2.33 from stat/lstat/
# fstat, rewrites the matching .gnu.version_r entry, refreshes the
# Vernaux hash). See radxa_a733_scripts/README.md for the full rationale.
need_patch=0
[[ ! -d "$patched_sdk_dir" ]] && need_patch=1
[[ -d "$patched_sdk_dir" && "$VIV_SDK_LIB_DIR/libGAL.so" -nt "$patched_sdk_dir/libGAL.so" ]] && need_patch=1
if [[ "$need_patch" == 1 ]]; then
  echo "[mirror] $VIV_SDK_LIB_DIR -> $patched_sdk_dir (libGAL.so patched)" >&2
  rm -rf "$patched_sdk_dir"
  mkdir -p "$patched_sdk_dir"
  for entry in "$VIV_SDK_LIB_DIR"/*; do
    name=$(basename "$entry")
    if [[ "$name" == "libGAL.so" ]]; then
      bash "$setup_dir/patch_libgal.bash" "$entry" "$patched_sdk_dir/$name"
    else
      ln -s "$entry" "$patched_sdk_dir/$name"
    fi
  done
fi

###############################################################################
# Decode + run
###############################################################################

input_bin="$(mktemp /tmp/timvx-input-XXXXXX.bin)"
if [[ "$keep_input" == 1 ]]; then
  echo "input bin (kept): $input_bin" >&2
else
  trap 'rm -f "$input_bin"' EXIT
fi

norm_flag=()
[[ "$no_norm" == 1 ]] && norm_flag=("--no-norm")

"$helper_bin" "$image" "$input_bin" "${norm_flag[@]}"

echo "---" >&2
echo "running $runner $input_bin" >&2
echo "  LD_LIBRARY_PATH += $timvx_lib_dir:$patched_sdk_dir" >&2
echo "  LD_PRELOAD     += $shim_so" >&2
echo "---" >&2

LD_PRELOAD="$shim_so${LD_PRELOAD:+:$LD_PRELOAD}" \
LD_LIBRARY_PATH="$timvx_lib_dir:$patched_sdk_dir:${LD_LIBRARY_PATH:-}" \
  "$runner" "$input_bin"
