// runner_main.cpp — auto-generated by lower_sample.bash. Edits welcome,
// the next regeneration will overwrite. The script substitutes four
// markers (BASE, FUNC_NAME, INPUT_SPECS, INPUT_ARGS) at the appropriate
// places below. See the kInputs initializer and the call-site to spot
// what was generated.
//
// Default behavior:
//   1. argv[1..N] are paths to raw binary blobs, one per non-const
//      function argument (image input plus any args the source MLIR
//      didn't fold into tosa.const — typical case is BatchNorm running
//      stats from frontends like torch-mlir). Element types match the
//      MLIR signature (parsed at lowering time into the kInputs init below).
//   2. Construct a tim::vx::Graph; build N INPUT tensors with the
//      configured shapes; copy each blob into its tensor.
//   3. Call __FUNC_NAME__(graph, inputs[0], ..., inputs[N-1]).
//      tosa.const data is already baked into the lowered function as
//      static arrays — no separate weights file needed. The lowering
//      pass also marks the func.return tensor as TensorAttribute::OUTPUT
//      so it can be read back via CopyDataFromTensor after Run().
//   4. Compile() + Run(); print output shape, first values, argmax,
//      min/max/mean to stdout.

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iterator>
#include <memory>
#include <numeric>
#include <vector>

#include "tim/vx/context.h"
#include "tim/vx/graph.h"
#include "tim/vx/tensor.h"
#include "tim/vx/types.h"

#include "timvx_runtime.h"
#include "__BASE__.func.cpp"

namespace {

struct InputSpec {
  std::vector<uint32_t> shape;
  tim::vx::DataType     dtype;
  // For quantized models: the (scale, zp) the network was calibrated for.
  // Set to (0.0, 0) to mean "no quant" — the runner skips Quantization()
  // on the spec in that case.
  double  quant_scale = 0.0;
  int32_t quant_zp    = 0;
};

// Parsed from the timvx MLIR's function signature; one entry per non-graph
// argument, in declaration order. To override (e.g. for a non-FP32 model),
// regenerate this file or hand-edit.
const std::vector<InputSpec> kInputs = {
__INPUT_SPECS__
};

constexpr size_t kPrintFirst = 16;

std::vector<uint8_t> read_file(const char* path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) {
    std::fprintf(stderr, "cannot open input: %s\n", path);
    std::exit(1);
  }
  std::streamsize n = f.tellg();
  f.seekg(0, std::ios::beg);
  std::vector<uint8_t> buf(static_cast<size_t>(n));
  f.read(reinterpret_cast<char*>(buf.data()), n);
  return buf;
}

void print_output(const std::shared_ptr<tim::vx::Tensor>& t) {
  const auto& shape = t->GetShape();
  size_t numel = 1;
  for (auto d : shape) numel *= d;

  std::printf("output shape: {");
  for (size_t i = 0; i < shape.size(); ++i)
    std::printf("%s%u", i ? ", " : "", shape[i]);
  std::printf("}, %zu elements\n", numel);
  if (numel == 0) return;

  // Read in the tensor's actual storage type, then dequantize / convert to
  // float for human-friendly summary stats. Quant info on the tensor's
  // spec gives us (scale, zp); for unquantized outputs we treat it as
  // identity.
  auto dtype = t->GetDataType();
  auto quant = t->GetQuantization();
  float scale = 1.0f;
  int32_t zp = 0;
  if (quant.Type() != tim::vx::QuantType::NONE && !quant.Scales().empty()) {
    scale = quant.Scales()[0];
    if (!quant.ZeroPoints().empty()) zp = quant.ZeroPoints()[0];
  }

  std::vector<float> buf(numel);
  auto dequant_into = [&](auto raw) {
    for (size_t i = 0; i < numel; ++i)
      buf[i] = (static_cast<float>(raw[i]) - static_cast<float>(zp)) * scale;
  };
  if (dtype == tim::vx::DataType::FLOAT32) {
    if (!t->CopyDataFromTensor(buf.data())) {
      std::fprintf(stderr, "CopyDataFromTensor failed\n"); std::exit(3);
    }
  } else if (dtype == tim::vx::DataType::INT8) {
    std::vector<int8_t> raw(numel);
    if (!t->CopyDataFromTensor(raw.data())) {
      std::fprintf(stderr, "CopyDataFromTensor failed\n"); std::exit(3);
    }
    dequant_into(raw);
  } else if (dtype == tim::vx::DataType::UINT8) {
    std::vector<uint8_t> raw(numel);
    if (!t->CopyDataFromTensor(raw.data())) {
      std::fprintf(stderr, "CopyDataFromTensor failed\n"); std::exit(3);
    }
    dequant_into(raw);
  } else {
    std::fprintf(stderr,
                 "print_output: unsupported dtype %d; raw bytes only.\n",
                 static_cast<int>(dtype));
    return;
  }

  size_t print_n = std::min(numel, kPrintFirst);
  std::printf("first %zu values (dequantized): [", print_n);
  for (size_t i = 0; i < print_n; ++i)
    std::printf("%s%.6f", i ? ", " : "", buf[i]);
  std::printf("%s]\n", numel > print_n ? ", ..." : "");

  auto max_it = std::max_element(buf.begin(), buf.end());
  auto min_it = std::min_element(buf.begin(), buf.end());
  size_t argmax = static_cast<size_t>(std::distance(buf.begin(), max_it));
  float sum = std::accumulate(buf.begin(), buf.end(), 0.0f);
  std::printf("argmax: %zu (value=%.6f)\n", argmax, *max_it);
  std::printf("min=%.6f  max=%.6f  mean=%.6f\n",
              *min_it, *max_it, sum / static_cast<float>(numel));
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != static_cast<int>(kInputs.size()) + 1) {
    std::fprintf(stderr, "usage: %s", argv[0]);
    for (size_t i = 0; i < kInputs.size(); ++i)
      std::fprintf(stderr, " <input%zu.bin>", i);
    std::fprintf(stderr,
                 "\n  expected %zu raw-binary inputs, one per non-graph "
                 "function argument.\n",
                 kInputs.size());
    return 2;
  }

  auto ctx = tim::vx::Context::Create();
  if (!ctx) { std::fprintf(stderr, "Context::Create failed\n"); return 1; }

  auto graph = ctx->CreateGraph();
  if (!graph) { std::fprintf(stderr, "ctx->CreateGraph failed\n"); return 1; }

  std::vector<std::shared_ptr<tim::vx::Tensor>> inputs;
  inputs.reserve(kInputs.size());
  for (size_t i = 0; i < kInputs.size(); ++i) {
    auto raw = read_file(argv[i + 1]);
    auto spec = (kInputs[i].quant_scale != 0.0)
        ? tim::vx::TensorSpec(
              kInputs[i].dtype, kInputs[i].shape,
              tim::vx::TensorAttribute::INPUT,
              tim::vx::Quantization(tim::vx::QuantType::ASYMMETRIC,
                                     static_cast<float>(kInputs[i].quant_scale),
                                     kInputs[i].quant_zp))
        : tim::vx::TensorSpec(kInputs[i].dtype, kInputs[i].shape,
                              tim::vx::TensorAttribute::INPUT);
    auto t = graph->CreateTensor(spec);
    if (!t->CopyDataToTensor(raw.data(),
                             static_cast<uint32_t>(raw.size()))) {
      std::fprintf(stderr,
                   "CopyDataToTensor failed for input %zu (%zu bytes)\n",
                   i, raw.size());
      return 3;
    }
    inputs.push_back(t);
  }

  auto output = __FUNC_NAME__(graph, __INPUT_ARGS__);

  if (!graph->Compile()) {
    std::fprintf(stderr, "graph->Compile failed\n");
    return 3;
  }
  if (!graph->Run()) {
    std::fprintf(stderr, "graph->Run failed\n");
    return 3;
  }

  print_output(output);
  return 0;
}
