// Declaration: This file is partially AI-generated and reviewed by human.
// namely, the AI wired the benchmark-related code segments in, and
// wrote the argument parsing, i.e. mostly benchmarking and peripherals.
// runner_main.cpp — auto-generated by lower_to_timvx.py. Edits welcome,
// the next regeneration will overwrite. The script substitutes four
// markers (BASE, FUNC_NAME, INPUT_SPECS, INPUT_ARGS) at the appropriate
// places below.
//
// Run modes
// =========
//
//   1. one-shot (legacy):
//        runner <input0.bin> [<input1.bin> ...]
//      One inference, print summary, exit. argv blobs are raw MLIR-row-
//      major bytes, one per non-graph function argument.
//
//   2. one-shot via orchestrator (CPU pre/post folded around NPU):
//        runner --mode <mode-name> <input0.bin> [<input1.bin> ...]
//      Same single inference but routed through the configurable
//      orchestrator — primarily useful when paired with `--bench`.
//
//   3. benchmark:
//        runner --mode <mode-name> --bench <N> <input0.bin> ...
//      Submits N copies of the input through the selected orchestrator
//      to measure throughput. Modes: 4 orchestration strategies ×
//      4 pre/post backends — see `pipeline/factory.h`.
//
//      mode-name ∈ {cpu-*, cpu_zero_copy-*, ppu-*, ppu_zero_copy-*}
//                  × {-sequential, -pipeline, -pool, -hybrid}
//
//   4. eval (one-time accuracy sweep):
//        runner --eval-dir <dir> --labels <file.json>
//               [--limit <N>] [--passthrough]
//      Walks the dir of JPEGs (or .bin tensors with --passthrough) and
//      accumulates top-1 / top-5 against labels[stem]. Hardcoded to
//      mode=cpu-sequential. Plumbing in `pipeline/eval.h`.
//
// All pipeline plumbing lives under `pipeline/` headers. This file only
// declares the auto-generated `kInputs` and dispatches argv into one of
// the four run modes above.

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

#include "tim/vx/context.h"
#include "tim/vx/graph.h"
#include "tim/vx/tensor.h"
#include "tim/vx/types.h"

#include "timvx_runtime.h"
#include "__BASE__.func.cpp"

#include "pipeline/benchmark.h"
#include "pipeline/byte_layout.h"
#include "pipeline/diag.h"
#include "pipeline/eval.h"
#include "pipeline/factory.h"
#include "pipeline/input_spec.h"
#include "pipeline/orchestrator.h"
#include "pipeline/postproc.h"
#include "pipeline/preproc.h"
#include "pipeline/tensor_io.h"

namespace tp = timvx_pipeline;
using InputSpec = tp::InputSpec;  // keep the unqualified name so
                                   // run_timvx.py's `kInputs` regex
                                   // (which looks for `InputSpec`
                                   // without a namespace prefix) keeps
                                   // matching after the pipeline/
                                   // reorganization.

namespace {

// Parsed from the timvx MLIR's function signature; one entry per
// non-graph argument, in declaration order. To override (e.g. for a
// non-FP32 model), regenerate this file or hand-edit.
const std::vector<InputSpec> kInputs = {
__INPUT_SPECS__
};

void usage(const char* argv0) {
  std::fprintf(stderr, "usage:\n");
  std::fprintf(stderr, "  one-shot:    %s", argv0);
  for (size_t i = 0; i < kInputs.size(); ++i)
    std::fprintf(stderr, " <input%zu.bin>", i);
  std::fprintf(stderr, "\n");
  std::fprintf(stderr, "  benchmark:   %s --mode <mode> --bench <N> "
               "[--warmup <W>] <image.jpg>\n", argv0);
  std::fprintf(stderr, "  eval:        %s --eval-dir <dir> --labels <file.json> "
               "[--limit <N>] [--passthrough]\n", argv0);
  std::fprintf(stderr,
               "  modes:       {cpu,cpu_zero_copy,ppu,ppu_zero_copy}-"
               "{sequential,pipeline,pool,hybrid}\n");
}

// Argument parse → mode + bench iters + warmup + first-input argv index.
struct ParsedArgs {
  std::string mode;            // empty = no orchestrator (legacy one-shot)
  size_t      bench_iters = 0; // 0 = single-shot
  size_t      warmup_iters = 0;
  // Eval mode: when eval_dir is non-empty, runner walks the dir, runs each
  // JPEG through the cpu-sequential orchestrator, accumulates top1/top5
  // against labels[stem]. Mutually exclusive with --bench / argv input blobs.
  std::string eval_dir;
  std::string eval_labels;
  size_t      eval_limit = 0;  // 0 = no limit
  bool        eval_passthrough = false;  // .bin files, bypass C++ preproc
  int         input_argv_start = 1;
  bool        ok = false;
};
ParsedArgs parse_args(int argc, char** argv) {
  ParsedArgs p;
  int i = 1;
  while (i < argc) {
    std::string a = argv[i];
    if (a == "--mode") {
      if (i + 1 >= argc) return p;
      p.mode = argv[i + 1];
      if (!tp::is_valid_mode(p.mode)) {
        std::fprintf(stderr, "unknown mode '%s'\n", p.mode.c_str());
        return p;
      }
      i += 2;
    } else if (a == "--bench") {
      if (i + 1 >= argc) return p;
      p.bench_iters = static_cast<size_t>(std::atoi(argv[i + 1]));
      if (p.bench_iters == 0) return p;
      i += 2;
    } else if (a == "--warmup") {
      if (i + 1 >= argc) return p;
      p.warmup_iters = static_cast<size_t>(std::atoi(argv[i + 1]));
      i += 2;
    } else if (a == "--eval-dir") {
      if (i + 1 >= argc) return p;
      p.eval_dir = argv[i + 1];
      i += 2;
    } else if (a == "--labels") {
      if (i + 1 >= argc) return p;
      p.eval_labels = argv[i + 1];
      i += 2;
    } else if (a == "--limit") {
      if (i + 1 >= argc) return p;
      p.eval_limit = static_cast<size_t>(std::atoi(argv[i + 1]));
      i += 2;
    } else if (a == "--passthrough") {
      p.eval_passthrough = true;
      i += 1;
    } else {
      p.input_argv_start = i;
      break;
    }
  }
  bool eval_mode = !p.eval_dir.empty();
  if (eval_mode) {
    if (p.eval_labels.empty()) {
      std::fprintf(stderr, "--eval-dir requires --labels\n");
      return p;
    }
    if (!p.mode.empty() || p.bench_iters > 0) {
      std::fprintf(stderr,
                   "--eval-dir is mutually exclusive with --mode / --bench "
                   "(eval is hardcoded to cpu-sequential)\n");
      return p;
    }
  } else {
    // One positional file argument expected (legacy multi-input models
    // are still handled by run_legacy_one_shot, which takes kInputs.size()
    // positional argv blobs). For orchestrated / bench modes we always
    // have a single input.
    int n_inputs = argc - p.input_argv_start;
    bool legacy_path = p.mode.empty();
    int expected = legacy_path ? static_cast<int>(kInputs.size()) : 1;
    if (n_inputs != expected) return p;
  }
  p.ok = true;
  return p;
}

// Build the (Graph, inputs[], output) triple. Shared between every run mode.
struct BuiltGraph {
  std::shared_ptr<tim::vx::Context> ctx;
  std::shared_ptr<tim::vx::Graph>   graph;
  std::vector<std::shared_ptr<tim::vx::Tensor>> inputs;
  std::shared_ptr<tim::vx::Tensor>  output;
};
// `use_iotensor` selects between regular `CreateTensor` (the copy
// path: CopyDataToTensor moves bytes from a host buffer into NPU-
// managed memory each Run) and `CreateIOTensor(spec, nullptr)` (the
// zero-copy path: the tensor's backing buffer is host memory that the
// CPU writes to directly, with SwapHandle rebinding per-Job). The
// zerocopy path requires post-build SwapHandle calls on g.output too;
// the orchestrator does that on every Run().
BuiltGraph build_graph(bool use_iotensor) {
  BuiltGraph g;
  g.ctx = tim::vx::Context::Create();
  if (!g.ctx) { std::fprintf(stderr, "Context::Create failed\n"); std::exit(1); }
  g.graph = g.ctx->CreateGraph();
  if (!g.graph) { std::fprintf(stderr, "CreateGraph failed\n"); std::exit(1); }

  g.inputs.reserve(kInputs.size());
  for (size_t i = 0; i < kInputs.size(); ++i) {
    auto spec = (kInputs[i].quant_scale != 0.0)
        ? tim::vx::TensorSpec(
              kInputs[i].dtype, kInputs[i].shape,
              tim::vx::TensorAttribute::INPUT,
              tim::vx::Quantization(tim::vx::QuantType::ASYMMETRIC,
                                     static_cast<float>(kInputs[i].quant_scale),
                                     kInputs[i].quant_zp))
        : tim::vx::TensorSpec(kInputs[i].dtype, kInputs[i].shape,
                              tim::vx::TensorAttribute::INPUT);
    // CreateIOTensor with a NULL initial pointer lets us SwapHandle to
    // per-Job buffers later. CreateTensor on an INPUT spec is the
    // legacy non-zerocopy path.
    if (use_iotensor) {
      g.inputs.push_back(g.graph->CreateIOTensor(spec, /*data=*/nullptr));
    } else {
      g.inputs.push_back(g.graph->CreateTensor(spec));
    }
  }

  using Clock = std::chrono::steady_clock;
  std::printf("[stage] building graph\n"); std::fflush(stdout);
  auto t_build = Clock::now();
  // `inputs` alias for the __INPUT_ARGS__ substitution (which emits
  // `inputs[0], inputs[1], ...`).
  auto& inputs = g.inputs;
  g.output = __FUNC_NAME__(g.graph, __INPUT_ARGS__);
  tp::print_stage("graph built", tp::msSince(t_build));

  std::printf("[stage] compiling\n"); std::fflush(stdout);
  auto t_compile = Clock::now();
  if (!g.graph->Compile()) {
    std::fprintf(stderr, "graph->Compile failed\n");
    std::exit(3);
  }
  tp::print_stage("compile done", tp::msSince(t_compile));
  return g;
}

// One-shot legacy path. No orchestrator: layout-convert in main and call
// Run() directly. Matches the original runner_main.cpp behavior bit-for-
// bit so we can A/B against orchestrator paths if needed.
int run_legacy_one_shot(BuiltGraph& g, int argc, char** argv, int argv_start) {
  std::vector<std::vector<uint8_t>> input_blobs;
  input_blobs.reserve(kInputs.size());
  for (size_t i = 0; i < kInputs.size(); ++i) {
    input_blobs.push_back(tp::read_file(argv[argv_start + static_cast<int>(i)]));
  }
  for (size_t i = 0; i < g.inputs.size(); ++i) {
    size_t elem = tp::bytesPerElem(kInputs[i].dtype);
    std::vector<uint8_t> tvx_bytes(input_blobs[i].size());
    // Native (folded-transpose) inputs already carry TIM-VX innermost-
    // first shape, so the blob is expected to be in that byte order
    // already — skip the MLIR→TIM-VX flip. Legacy inputs get the flip.
    if (kInputs[i].timvx_native_layout) {
      tvx_bytes = input_blobs[i];
    } else {
      tp::layoutConvert(input_blobs[i].data(), tvx_bytes.data(),
                        kInputs[i].shape, elem, /*from_mlir_to_tvx=*/true);
    }
    if (!g.inputs[i]->CopyDataToTensor(
            tvx_bytes.data(),
            static_cast<uint32_t>(tvx_bytes.size()))) {
      std::fprintf(stderr,
                   "CopyDataToTensor failed for input %zu (%zu bytes)\n",
                   i, tvx_bytes.size());
      return 3;
    }
  }

  using Clock = std::chrono::steady_clock;
  std::printf("[stage] running inference\n"); std::fflush(stdout);
  auto t_run = Clock::now();
  if (!g.graph->Run()) {
    std::fprintf(stderr, "graph->Run failed after %.2f ms\n",
                 tp::msSince(t_run));
    std::fflush(stderr);
    // Skip the C++ destructor chain — failed Run() can leave commands
    // in flight that the dtor never reaps (observed hang requiring two
    // Ctrl+C's). _exit lets the kernel reap GPU FDs.
    std::_Exit(3);
  }
  double run_ms = tp::msSince(t_run);
  tp::print_stage("run done", run_ms);
  tp::print_output(g.output);
  std::fflush(stdout);
  std::printf("[summary] run=%.2fms\n", run_ms);
  return 0;
}

// Orchestrated run (one-shot or bench). Picks the right Backend+
// Orchestrator from the mode string and submits N inputs.
int run_orchestrated(BuiltGraph& g, const std::string& mode,
                      size_t bench_iters, size_t warmup_iters,
                      int argc, char** argv, int argv_start) {
  (void)argc;
  bool zerocopy = tp::mode_is_zerocopy(mode);
  if (kInputs.size() != 1) {
    std::fprintf(stderr,
                 "orchestrator modes require exactly one input tensor "
                 "(model has %zu)\n", kInputs.size());
    return 2;
  }
  // Load the one input from argv.
  auto raw = tp::read_file(argv[argv_start]);
  // Output tensor's quant for PPU postproc.
  auto quant = g.output->GetQuantization();
  double Sout = 0.0; int32_t Zout = 0;
  if (quant.Type() != tim::vx::QuantType::NONE && !quant.Scales().empty()) {
    Sout = quant.Scales()[0];
    if (!quant.ZeroPoints().empty()) Zout = quant.ZeroPoints()[0];
  }
  uint32_t num_classes = 1;
  for (auto d : g.output->GetShape()) num_classes *= d;

  // For PPU modes the preproc's TIM-VX graph is sized for a fixed
  // (src_w, src_h) input. Probe the JPEG header once so we hand the
  // factory the correct dimensions; for non-PPU modes this is a cheap
  // no-op (the values aren't consulted).
  std::array<uint32_t, 2> ppu_src_shape = tp::kPpuSourceShapeFallback;
  if (tp::mode_is_ppu(mode)) {
    tp::RgbImage probe = tp::decode_jpeg(raw);
    if (probe.data.empty()) {
      std::fprintf(stderr,
                   "[orch %s] could not probe JPEG dims from input\n",
                   mode.c_str());
      return 3;
    }
    ppu_src_shape = {static_cast<uint32_t>(probe.width),
                     static_cast<uint32_t>(probe.height)};
    std::printf("[stage] PPU preproc src shape: %ux%ux3\n",
                ppu_src_shape[0], ppu_src_shape[1]);
    std::fflush(stdout);
  }

  auto backend = tp::make_backend(mode, kInputs[0], num_classes, Sout, Zout,
                                   ppu_src_shape);
  if (!backend.pre || !backend.post) return 2;

  tp::ModeConfig cfg{mode};
  // Allow env override for the pool/hybrid worker count. Both
  // strategies use the same knob now (the new ThreadPool builds N
  // graphs; the renamed Hybrid runs N pre→infer→post threads against
  // one shared graph).
  if (const char* s = std::getenv("TIMVX_POOL_WORKERS"))
    cfg.num_pool_workers = static_cast<size_t>(std::atoi(s));

  // Zerocopy path: allocate an IoBufferPool sized to the strategy's
  // worst-case in-flight Job count. The pool's slot count is set by
  // `default_iopool_slots(cfg)` and can be overridden via
  // `TIMVX_IOPOOL_SLOTS=N` in the environment (useful for
  // characterising the effect of pool starvation on throughput).
  std::unique_ptr<tp::IoBufferPool> pool;
  if (zerocopy) {
    size_t slots = tp::default_iopool_slots(cfg);
    if (const char* s = std::getenv("TIMVX_IOPOOL_SLOTS")) {
      slots = static_cast<size_t>(std::atoi(s));
    }
    cfg.iopool_slots = slots;
    size_t in_bytes  = backend.pre->expected_output_bytes();
    size_t out_bytes_per_slot = 1;
    for (auto d : g.output->GetShape()) out_bytes_per_slot *= d;
    out_bytes_per_slot *= tp::bytesPerElem(g.output->GetDataType());
    // pre_in_bytes is non-zero only for PPU zerocopy modes (where the
    // PPU graph's INPUT tensor is bound per-slot to the decoded JPEG
    // bytes). CPU zerocopy returns 0 from expected_pre_in_bytes().
    size_t pre_in_bytes = backend.pre->expected_pre_in_bytes();
    pool = std::make_unique<tp::IoBufferPool>(slots, in_bytes,
                                                out_bytes_per_slot,
                                                pre_in_bytes);
    if (pre_in_bytes != 0) {
      std::printf("[stage] zerocopy iobuf pool: %zu slots × "
                  "(pre_in=%zu, in=%zu, out=%zu) bytes\n",
                  slots, pre_in_bytes, in_bytes, out_bytes_per_slot);
    } else {
      std::printf("[stage] zerocopy iobuf pool: %zu slots × "
                  "(in=%zu, out=%zu) bytes\n",
                  slots, in_bytes, out_bytes_per_slot);
    }
    std::fflush(stdout);
  }

  // pool strategy: build extra graph copies (one per worker) so each
  // worker has its own tim::vx::Graph for concurrent Run(). Other
  // strategies reuse `g` as a single shared instance. The first
  // WorkerGraph always points at `g`; pool mode appends N-1 more.
  std::vector<tp::WorkerGraph> worker_graphs;
  worker_graphs.push_back({g.ctx, g.graph, g.inputs[0], g.output});
  size_t need_graphs = tp::graphs_needed(cfg);
  if (need_graphs > 1) {
    std::printf("[stage] building %zu additional graph instance(s) "
                "for pool mode\n", need_graphs - 1);
    std::fflush(stdout);
    // Each extra graph must match the first graph's input-tensor
    // attribute (CreateTensor vs CreateIOTensor) so SwapHandle works
    // the same way across workers. mode_is_zerocopy drives that.
    bool use_iotensor = tp::mode_is_zerocopy(mode);
    for (size_t i = 1; i < need_graphs; ++i) {
      BuiltGraph extra = build_graph(use_iotensor);
      worker_graphs.push_back({extra.ctx, extra.graph,
                                extra.inputs[0], extra.output});
    }
  }

  auto orch = tp::make_orchestrator(cfg, std::move(worker_graphs),
                                     backend.pre.get(), backend.post.get(),
                                     pool.get());
  if (!orch) return 2;

  // Validate input size matches the preprocessor's expectation. JPEG
  // processors return 0 (variable; decoder reads dims from the header)
  // so we skip the check in that case.
  size_t want = backend.pre->expected_input_bytes();
  if (want != 0 && raw.size() != want) {
    std::fprintf(stderr,
                 "[orch %s] input size mismatch: file has %zu bytes, "
                 "preprocessor expects %zu\n",
                 mode.c_str(), raw.size(), want);
    return 3;
  }

  size_t iters = bench_iters == 0 ? 1 : bench_iters;
  std::printf("[stage] orchestrator '%s' (pre=%s post=%s)  iters=%zu  "
              "warmup=%zu\n",
              orch->name(), backend.pre->name(), backend.post->name(),
              iters, warmup_iters);
  std::fflush(stdout);

  auto stats = tp::run_benchmark(*orch, std::move(raw), iters, warmup_iters);
  tp::print_bench(mode.c_str(), stats);
  return stats.n_fail == 0 ? 0 : 3;
}

} // namespace

int main(int argc, char** argv) {
  std::setvbuf(stdout, nullptr, _IONBF, 0);
  auto args = parse_args(argc, argv);
  if (!args.ok) { usage(argv[0]); return 2; }
  // build_graph decides between CreateTensor (copy path) and
  // CreateIOTensor (zerocopy path) for the input tensor based on the
  // chosen orchestration mode — this has to be known BEFORE the graph
  // body is built so the input tensor's flags are right at compile time.
  bool use_iotensor = !args.mode.empty() && tp::mode_is_zerocopy(args.mode);
  auto g = build_graph(use_iotensor);
  if (!args.eval_dir.empty()) {
    // Eval is single-input only; build_graph already produced g.inputs[0]
    // with the cpu (non-zerocopy) path since args.mode is empty here.
    if (kInputs.size() != 1) {
      std::fprintf(stderr, "--eval-dir requires single-input model "
                            "(have %zu inputs)\n", kInputs.size());
      return 2;
    }
    return tp::run_eval(g.ctx, g.graph, g.inputs[0], g.output, kInputs[0],
                        args.eval_dir, args.eval_labels, args.eval_limit,
                        args.eval_passthrough);
  }
  if (!args.mode.empty()) {
    return run_orchestrated(g, args.mode, args.bench_iters,
                             args.warmup_iters,
                             argc, argv, args.input_argv_start);
  }
  return run_legacy_one_shot(g, argc, argv, args.input_argv_start);
}
